### ISSUE TITLE
Reserva as vezes é cadastrada no dia anterior

### ISSUE THREAD

**Issue by ericbreno** [estacioneto/SCORE#33]
Ao criar uma reserva ela fica no dia anterior ao selecionado, dependendo do horário

**Comment by velmer** [comment]
Tava dando uma olhada nisso, o método toGMTString() de um objeto Moment - que é o objeto usado por datas no FullCalendar -  retorna a data e horário independente do fuso horário, ele corrige bonitinho, então não precisamos incrementar 3 horas para ficar correto. Porém, ele retorna em string, teríamos apenas que fazer manipulação da mesma

**Comment by estacioneto** [comment]
Ainda não foi solucionado?

**Comment by estacioneto** [comment]
[https://fullcalendar.io/docs/timezone/timezone/](url)

**Comment by estacioneto** [comment]
Problema resolvido.
[https://github.com/estacioneto/SCORE/pull/67](url)
