### ISSUE TITLE
erro no cadastro (prof campelo)

### ISSUE THREAD

**Issue by cadocapires** [estacioneto/SCORE#51]
fiz minha "inscrição" com email @computacao, defini minha senha, recebi o email para confirmação, confirmei.

porém, depois não consegui fazer login:

SENTIMOS MUITO, MAS ALGO DEU ERRADO AO TENTAR ENTRAR.

cliquei em "esqueceu sua senha?", recebi um email para resetar a senha, resetei.

porém, depois não consegui fazer login:

SENTIMOS MUITO, MAS ALGO DEU ERRADO AO TENTAR ENTRAR.

**Comment by ericbreno** [comment]
O problema foi identificado e corrigido. Login e cadastro devem estar funcionando corretamente agora.
