### ISSUE TITLE
Carregamento independente de imagens

### ISSUE THREAD

**Issue by ericbreno** [estacioneto/SCORE#81]
As imagens dos auditórios deveriam ser carregadas de forma independente da listagem, para que não travasse o usuário de poder visualizar sua agenda. Uma solução seria não trazer as imagens na consulta da listagem, e apresentar um spinner enquanto elas carregam.

**Comment by estacioneto** [comment]
Corrigido na forma que a [listagem retorna o Local com apenas a sua imagem principal](https://github.com/estacioneto/SCORE/commit/d3528cbff09fea761969a9112ca1013bac6dce14#diff-4ac32a78649ca5bdd8e0ba38b7006a1e).
